const gradedArticleLibraries = [
  {
    id: "builtin-articles-junior-basic",
    type: "articles",
    name: "中考基础 · A2",
    format: "原创 · 分级",
    level: "中考基础 · A2",
    cefr: "A2",
    description: "贴近校园与日常生活的短篇听读材料，句式清晰，适合中考基础训练。",
    items: [
      {
        id: "junior-basic-library-card",
        level: "中考基础 · A2",
        cefr: "A2",
        estimatedWords: 113,
        title: "My First Library Card",
        titleZh: "我的第一张借书证",
        genre: "听力短文",
        topic: "人与社会",
        summary: "一名学生第一次独立办理借书证，并学会遵守图书馆规则。",
        sentences: [
          { en: "On Saturday morning, my father took me to the new library near our home.", zh: "星期六早上，爸爸带我去了家附近的新图书馆。" },
          { en: "The building was bright, quiet, and full of colorful books.", zh: "大楼明亮又安静，里面摆满了各种各样的书。" },
          { en: "A librarian showed me how to get my first library card.", zh: "一位图书管理员教我怎样办理第一张借书证。" },
          { en: "I wrote down my name and phone number on a small form.", zh: "我在一张小表格上写下了姓名和电话号码。" },
          { en: "Then she explained that I could borrow four books for three weeks.", zh: "然后她说明，我每次可以借四本书，借期为三周。" },
          { en: "I chose a story about space and a book about animals.", zh: "我选了一本太空故事和一本动物书。" },
          { en: "Before I left, I checked the return date carefully.", zh: "离开前，我认真查看了还书日期。" },
          { en: "The librarian smiled and said, \"Books are good friends when you care for them.\"", zh: "图书管理员微笑着说：“只要你好好爱护，书就是好朋友。”" },
          { en: "I carried the books home and started reading after lunch.", zh: "我把书带回家，午饭后就开始阅读。" },
          { en: "That little card opened a much bigger world for me.", zh: "那张小小的借书证为我打开了一个更大的世界。" },
        ],
      },
      {
        id: "junior-basic-phone-free-morning",
        level: "中考基础 · A2",
        cefr: "A2",
        estimatedWords: 103,
        title: "A Morning Without My Phone",
        titleZh: "没有手机的一个早晨",
        genre: "记叙文",
        topic: "人与自我",
        summary: "一次忘带手机的经历，让学生重新发现身边的人和事。",
        sentences: [
          { en: "Last Tuesday, I left my phone at home by mistake.", zh: "上周二，我不小心把手机落在了家里。" },
          { en: "At first, I felt worried because I usually checked it on the bus.", zh: "起初我很不安，因为我平时总会在公交车上看手机。" },
          { en: "With no screen to watch, I looked out of the window instead.", zh: "没有屏幕可看，我便转而望向窗外。" },
          { en: "I noticed the morning sun shining on the river.", zh: "我注意到晨光正洒在河面上。" },
          { en: "An old man beside me asked about my school bag.", zh: "坐在我旁边的一位老人问起了我的书包。" },
          { en: "We talked about his school days and laughed together.", zh: "我们聊起他的学生时代，还一起笑了起来。" },
          { en: "During the break, I played basketball instead of reading messages.", zh: "课间时，我没有看消息，而是去打了篮球。" },
          { en: "The morning seemed longer, but it also felt calmer.", zh: "这个早晨似乎变长了，却也让我感觉更平静。" },
          { en: "When I got home, there were only two new messages.", zh: "回到家时，手机里只有两条新消息。" },
          { en: "I learned that I did not need my phone every minute.", zh: "我明白了，自己并不需要时时刻刻都拿着手机。" },
        ],
      },
      {
        id: "junior-basic-roof-garden",
        level: "中考基础 · A2",
        cefr: "A2",
        estimatedWords: 102,
        title: "The Garden on Our Roof",
        titleZh: "我们的屋顶花园",
        genre: "阅读理解",
        topic: "人与自然",
        summary: "同学们把空屋顶改造成小花园，并在劳动中观察植物生长。",
        sentences: [
          { en: "There was once an empty roof above our school dining hall.", zh: "学校食堂上方曾经有一处空屋顶。" },
          { en: "This spring, our science teacher asked us to turn it into a garden.", zh: "今年春天，科学老师让我们把它变成一座花园。" },
          { en: "We carried up boxes, soil, and small watering cans.", zh: "我们把种植箱、泥土和小水壶搬到了屋顶。" },
          { en: "Some students planted tomatoes, while others planted flowers for bees.", zh: "一些同学种番茄，另一些同学种能吸引蜜蜂的花。" },
          { en: "My job was to water the plants every Wednesday.", zh: "我的任务是每周三给植物浇水。" },
          { en: "At first, the green leaves were no bigger than my hand.", zh: "起初，那些绿叶还没有我的手掌大。" },
          { en: "After several sunny weeks, yellow flowers appeared among them.", zh: "经过几个阳光充足的星期，绿叶间开出了黄色的小花。" },
          { en: "We also saw butterflies and birds visit the roof.", zh: "我们还看到蝴蝶和小鸟来到屋顶。" },
          { en: "The garden made the dining hall cooler on hot days.", zh: "在炎热的日子里，花园还让食堂变得更凉爽。" },
          { en: "It showed us that even a small space can help nature.", zh: "它让我们看到，即使一小块空间也能为自然出一份力。" },
        ],
      },
    ],
  },
  {
    id: "builtin-articles-junior-advanced",
    type: "articles",
    name: "中考提高 · A2+–B1",
    format: "原创 · 分级",
    level: "中考提高 · A2+–B1",
    cefr: "A2+–B1",
    description: "增加叙事细节、因果关系与说明性表达，适合中考提高训练。",
    items: [
      {
        id: "junior-advanced-window-seat",
        level: "中考提高 · A2+–B1",
        cefr: "A2+–B1",
        estimatedWords: 140,
        title: "The Seat by the Window",
        titleZh: "窗边的座位",
        genre: "听力故事",
        topic: "人与社会",
        summary: "一次主动让座带来温暖交谈，也改变了学生对陌生人的看法。",
        sentences: [
          { en: "On the train to Hangzhou, I was lucky enough to get a seat by the window.", zh: "在去杭州的火车上，我很幸运地坐到了窗边。" },
          { en: "I planned to take photos of the lakes and fields along the way.", zh: "我原计划一路拍摄湖泊和田野。" },
          { en: "Just before the train left, a woman came in with a little boy.", zh: "就在火车开动前，一位女士带着一个小男孩走了进来。" },
          { en: "Their seats were in different rows, and the boy looked nervous.", zh: "他们的座位不在同一排，小男孩显得很紧张。" },
          { en: "I offered him my window seat and moved next to his mother.", zh: "我把窗边的座位让给了他，自己坐到了他妈妈旁边。" },
          { en: "The boy pressed his face close to the glass and named everything he saw.", zh: "小男孩把脸贴近车窗，说出他看到的每一样东西。" },
          { en: "His excitement made everyone around us smile.", zh: "他的兴奋让周围的人都笑了起来。" },
          { en: "During the journey, his mother told me that it was his first train ride.", zh: "旅途中，他妈妈告诉我，这是他第一次坐火车。" },
          { en: "She thanked me and shared some homemade cookies with me.", zh: "她向我道谢，还和我分享了自制饼干。" },
          { en: "I took fewer photos than I had expected, but I remembered the journey more clearly.", zh: "我拍的照片比预想中少，但这段旅程却记得更加清楚。" },
          { en: "Giving up one good view helped me see something better: the joy of being kind.", zh: "放弃一次好风景，让我看到了更好的东西——善意带来的快乐。" },
        ],
      },
      {
        id: "junior-advanced-plan-week",
        level: "中考提高 · A2+–B1",
        cefr: "A2+–B1",
        estimatedWords: 135,
        title: "Learning to Plan My Week",
        titleZh: "学会规划一周",
        genre: "经验分享",
        topic: "人与自我",
        summary: "学生通过简单的周计划减少拖延，并为休息与爱好留出时间。",
        sentences: [
          { en: "I used to begin every Monday with a long list of things to do.", zh: "过去，我每到周一都会列出一长串待办事项。" },
          { en: "However, I often chose the easiest task first and left important work until Sunday night.", zh: "可是，我常常先做最容易的事，把重要任务拖到周日晚上。" },
          { en: "As a result, I felt busy all week but still finished very little.", zh: "结果，我整个星期都觉得很忙，却没有完成多少事情。" },
          { en: "My teacher suggested dividing my plan into three kinds of tasks.", zh: "老师建议我把计划分成三类任务。" },
          { en: "The first group included work that had to be done that day.", zh: "第一类是当天必须完成的事情。" },
          { en: "The second group included tasks that could be moved to another day.", zh: "第二类是可以调整到其他日期的任务。" },
          { en: "The last group was for rest, exercise, and hobbies.", zh: "最后一类留给休息、运动和兴趣爱好。" },
          { en: "I also started giving each task a realistic amount of time.", zh: "我还开始为每项任务安排合理的时间。" },
          { en: "After two weeks, I was no longer rushing through homework late at night.", zh: "两周后，我不再需要深夜匆忙赶作业了。" },
          { en: "I even had time to practice the guitar without feeling guilty.", zh: "我甚至能安心练吉他，不再觉得自己耽误了学习。" },
          { en: "A good plan did not make my week fuller; it made my choices clearer.", zh: "一份好计划并没有让我的一周更拥挤，而是让我的选择更清楚。" },
        ],
      },
      {
        id: "junior-advanced-city-trees",
        level: "中考提高 · A2+–B1",
        cefr: "A2+–B1",
        estimatedWords: 134,
        title: "Why City Trees Matter",
        titleZh: "城市树木为什么重要",
        genre: "说明文",
        topic: "人与自然",
        summary: "从降温、净化空气和提供栖息地等角度介绍城市树木的价值。",
        sentences: [
          { en: "A street without trees can feel much hotter than a street with plenty of shade.", zh: "没有树木的街道，往往比绿荫充足的街道热得多。" },
          { en: "This is because leaves block sunlight and release water into the air.", zh: "这是因为树叶能够遮挡阳光，并向空气中释放水分。" },
          { en: "Together, these actions help lower the temperature around buildings and roads.", zh: "这些作用共同降低了建筑物和道路周围的温度。" },
          { en: "City trees also catch some dust and take in carbon dioxide.", zh: "城市树木还能拦住一部分灰尘，并吸收二氧化碳。" },
          { en: "Their roots slow down rainwater, so less water rushes into drains at once.", zh: "树根能减缓雨水流动，因此不会有大量雨水同时涌入排水系统。" },
          { en: "Birds, insects, and other small animals use trees for food and shelter.", zh: "鸟类、昆虫和其他小动物也会在树上寻找食物和栖身之处。" },
          { en: "Trees can even make a neighborhood feel quieter and more welcoming.", zh: "树木甚至能让社区显得更安静、更宜居。" },
          { en: "Yet planting a tree is only the first step.", zh: "然而，种下一棵树只是第一步。" },
          { en: "Young trees need enough soil, regular water, and protection from damage.", zh: "幼树需要足够的土壤、定期浇水，还需要避免受到损伤。" },
          { en: "Local people can help by reporting broken branches and keeping rubbish away from roots.", zh: "居民可以报告断枝情况，并清理树根周围的垃圾。" },
          { en: "When a city looks after its trees, the trees look after the city in return.", zh: "当一座城市照料好树木时，树木也会反过来守护这座城市。" },
        ],
      },
    ],
  },
  {
    id: "builtin-articles-senior-basic",
    type: "articles",
    name: "高考基础 · B1",
    format: "原创 · 分级",
    level: "高考基础 · B1",
    cefr: "B1",
    description: "强化篇章结构、信息提取与观点理解，适合高考基础阅读和听力训练。",
    items: [
      {
        id: "senior-basic-radio-interview",
        level: "高考基础 · B1",
        cefr: "B1",
        estimatedWords: 163,
        title: "A Voice for the School",
        titleZh: "校园广播里的声音",
        genre: "听力访谈",
        topic: "人与自我",
        summary: "校园电台主持人分享克服紧张、准备采访和倾听他人的经验。",
        sentences: [
          { en: "When Mei joined the school radio station, she expected to spend most of her time choosing music.", zh: "梅加入校园广播站时，以为自己大部分时间都会用来选音乐。" },
          { en: "Instead, the teacher asked her to host a weekly interview program.", zh: "没想到，老师让她主持一档每周访谈节目。" },
          { en: "Mei was worried because her voice shook whenever she spoke in public.", zh: "梅很担心，因为她一公开讲话，声音就会发抖。" },
          { en: "For her first program, she interviewed the captain of the girls' basketball team.", zh: "第一期节目中，她采访了校女子篮球队队长。" },
          { en: "She prepared twenty questions, but her teacher told her to keep only six.", zh: "她准备了二十个问题，但老师让她只保留六个。" },
          { en: "Good interviews, the teacher explained, depend more on listening than on asking many questions.", zh: "老师解释说，好的采访更多依靠倾听，而不是提出很多问题。" },
          { en: "During the recording, Mei heard an unexpected story about the team's first defeat.", zh: "录音时，梅听到了球队首次失利的一段意外故事。" },
          { en: "She put aside her prepared list and asked how the players had encouraged one another.", zh: "她放下准备好的问题清单，追问队员们是怎样互相鼓励的。" },
          { en: "The captain's honest answer became the best part of the program.", zh: "队长真诚的回答成了整期节目最精彩的部分。" },
          { en: "Mei still felt nervous when the interview was broadcast, but she also felt proud.", zh: "采访播出时，梅仍然感到紧张，但也很自豪。" },
          { en: "Now she practices speaking clearly, while leaving enough silence for each guest to think.", zh: "现在她练习清楚表达，同时也会给嘉宾留下足够的思考时间。" },
          { en: "The radio station has taught her that confidence can begin with careful attention to someone else.", zh: "广播站让她懂得，自信可以从认真关注他人开始。" },
        ],
      },
      {
        id: "senior-basic-repair-cafe",
        level: "高考基础 · B1",
        cefr: "B1",
        estimatedWords: 167,
        title: "The Saturday Repair Café",
        titleZh: "周六维修咖啡馆",
        genre: "阅读理解",
        topic: "人与社会",
        summary: "社区志愿者帮助居民维修旧物，让技能、资源和邻里关系得到延续。",
        sentences: [
          { en: "Once a month, the community center in Green Street becomes a repair café.", zh: "每个月有一天，绿街社区中心都会变成一家“维修咖啡馆”。" },
          { en: "People arrive carrying lamps, clocks, toys, and clothes that no longer work properly.", zh: "人们带着不能正常使用的台灯、钟表、玩具和衣物来到这里。" },
          { en: "Instead of throwing these things away, they sit down with volunteers and try to repair them.", zh: "他们没有扔掉这些物品，而是与志愿者坐在一起尝试修理。" },
          { en: "Some volunteers understand electronics, while others are good at sewing or working with wood.", zh: "一些志愿者懂电子设备，另一些则擅长缝纫或木工。" },
          { en: "Visitors do not simply hand over an object and wait.", zh: "来访者并不是把物品交出去后只在一旁等待。" },
          { en: "They are invited to watch, ask questions, and learn how the repair is done.", zh: "他们会被邀请观看、提问，并学习维修过程。" },
          { en: "Not every object can be saved, but even an unsuccessful repair can teach a useful lesson.", zh: "并非每件物品都能修好，但即使维修失败，也能带来有用的经验。" },
          { en: "The café keeps waste out of local bins and helps families save money.", zh: "这家咖啡馆减少了本地垃圾，也帮助家庭节省开支。" },
          { en: "More importantly, it creates conversations between people who might never meet otherwise.", zh: "更重要的是，它让原本可能永远不会相识的人开始交流。" },
          { en: "A retired engineer may work beside a teenager who has never held a screwdriver.", zh: "一位退休工程师可能会和一个从未拿过螺丝刀的少年一起工作。" },
          { en: "By the end of the afternoon, both of them have shared something valuable.", zh: "到了下午结束时，两个人都分享了有价值的东西。" },
          { en: "The repair café shows that extending the life of an object can also strengthen the life of a community.", zh: "维修咖啡馆说明，延长物品寿命的同时，也能增强社区的活力。" },
        ],
      },
      {
        id: "senior-basic-river-returned",
        level: "高考基础 · B1",
        cefr: "B1",
        estimatedWords: 161,
        title: "When the River Came Back",
        titleZh: "河流重新归来",
        genre: "说明文",
        topic: "人与自然",
        summary: "一座小城通过自然化改造恢复河道，也重新建立居民与河流的联系。",
        sentences: [
          { en: "For many years, a narrow river flowed beneath a concrete cover in the town of Linton.", zh: "多年来，一条狭窄的河流一直在林顿镇的水泥盖板下流淌。" },
          { en: "Most residents walked over it every day without knowing it was there.", zh: "大多数居民每天从上面走过，却不知道河流的存在。" },
          { en: "When heavy rain caused repeated flooding, the town began searching for a better solution.", zh: "暴雨多次引发洪水后，小镇开始寻找更好的解决办法。" },
          { en: "Engineers suggested removing part of the cover and giving the river more space.", zh: "工程师建议拆除部分盖板，为河流留出更多空间。" },
          { en: "The plan sounded risky to some shop owners, who feared months of noise and fewer customers.", zh: "一些店主认为计划风险很大，他们担心数月的噪声会减少客流。" },
          { en: "Town leaders therefore divided the work into short stages and kept walking paths open.", zh: "因此，镇政府把工程分成几个短阶段，并一直保留步行通道。" },
          { en: "They added gentle riverbanks, native plants, and small pools where rainwater could collect.", zh: "他们修建了缓坡河岸，种植本地植物，还设置了可以蓄积雨水的小水池。" },
          { en: "Within a year, birds and insects returned to the area.", zh: "不到一年，鸟类和昆虫便重新回到了这里。" },
          { en: "Children began using the riverside path to walk to school.", zh: "孩子们开始沿着河边小路步行上学。" },
          { en: "During later storms, the wider channel carried water more safely through the town.", zh: "后来遇到暴雨时，拓宽后的河道能让雨水更安全地穿过小镇。" },
          { en: "The project did not return the river to exactly what it had been centuries ago.", zh: "这项工程并没有让河流完全恢复成数百年前的样子。" },
          { en: "It did, however, allow nature and daily town life to share the same space again.", zh: "但它确实让自然与小镇日常生活重新共享同一片空间。" },
        ],
      },
    ],
  },
  {
    id: "builtin-articles-senior-advanced",
    type: "articles",
    name: "高考提高 · B1+–B2",
    format: "原创 · 分级",
    level: "高考提高 · B1+–B2",
    cefr: "B1+–B2",
    description: "包含较长叙事、议论与科普语篇，训练推断、逻辑关系和主题概括。",
    items: [
      {
        id: "senior-advanced-lights-out",
        level: "高考提高 · B1+–B2",
        cefr: "B1+–B2",
        estimatedWords: 210,
        title: "When the Lights Went Out",
        titleZh: "停电之后",
        genre: "记叙文",
        topic: "人与社会",
        summary: "一次暴雨停电让公寓居民走出各自房间，在互助中建立新的联系。",
        sentences: [
          { en: "The storm arrived just after dinner, shaking the windows of our apartment building and filling the street with rain.", zh: "暴风雨在晚饭后不久到来，震动着公寓楼的窗户，也让街道被雨水淹没。" },
          { en: "A sudden flash lit the sky, and every lamp in the building went dark.", zh: "一道闪电突然照亮天空，楼里的所有灯随即熄灭。" },
          { en: "At first, people stayed behind their doors, waiting for the power to return.", zh: "起初，大家都留在门后，等待电力恢复。" },
          { en: "Then someone on the sixth floor called out that an older neighbor needed help with her oxygen machine.", zh: "随后，六楼有人喊道，一位年长的邻居需要帮助使用制氧机。" },
          { en: "Mr. Chen, who owned a small camping shop, brought a charged battery pack upstairs.", zh: "经营户外用品店的陈先生带着一块充好电的电池上了楼。" },
          { en: "Two students used phone lights to guide him safely along the stairs.", zh: "两名学生用手机灯光为他照亮楼梯。" },
          { en: "Meanwhile, families with gas stoves began heating water for people who could not cook.", zh: "与此同时，家里有燃气灶的住户开始为无法做饭的人烧热水。" },
          { en: "The manager opened the ground-floor meeting room, where everyone could sit together.", zh: "物业经理打开一楼会议室，让大家可以聚在一起。" },
          { en: "Children played card games, adults shared weather updates, and someone found an old guitar.", zh: "孩子们玩纸牌，大人们分享天气消息，还有人找来了一把旧吉他。" },
          { en: "Without the usual hum of machines, the building sounded strangely alive.", zh: "没有了机器平日的嗡鸣声，整栋楼反而显得格外有生气。" },
          { en: "Four hours later, the lights returned and people cheered.", zh: "四小时后，灯光恢复，大家欢呼起来。" },
          { en: "Yet nobody hurried back to an empty room right away.", zh: "然而，没有人立刻匆匆回到各自空荡荡的房间。" },
          { en: "The following weekend, residents created an emergency contact list and checked which neighbors might need support.", zh: "接下来的周末，居民们制作了紧急联系表，并确认哪些邻居可能需要帮助。" },
          { en: "They also planned a monthly shared dinner in the same meeting room.", zh: "他们还计划每月都在那间会议室举行一次聚餐。" },
          { en: "The storm had interrupted an ordinary evening, but it also revealed a community that had been waiting quietly behind closed doors.", zh: "暴风雨打断了一个普通的夜晚，却也让那个一直静静藏在一扇扇门后的社区显现出来。" },
        ],
      },
      {
        id: "senior-advanced-better-homework",
        level: "高考提高 · B1+–B2",
        cefr: "B1+–B2",
        estimatedWords: 215,
        title: "Could Homework Be Designed Differently?",
        titleZh: "作业能否换一种设计方式？",
        genre: "议论文",
        topic: "人与自我",
        summary: "文章讨论作业质量与数量的差别，并提出更有目的性的作业设计原则。",
        sentences: [
          { en: "Debates about homework often focus on a single question: should students receive more of it or less?", zh: "关于作业的讨论常常集中在一个问题上：学生应该多做一些，还是少做一些？" },
          { en: "That question matters, but it may hide a more useful one: what kind of homework actually supports learning?", zh: "这个问题固然重要，却可能掩盖了一个更有价值的问题：什么样的作业真正有助于学习？" },
          { en: "Repeating a skill can strengthen memory, especially when practice is spread across several days.", zh: "重复练习能够巩固记忆，尤其是把练习分散到几天完成时。" },
          { en: "However, a long set of nearly identical questions may add tiredness without adding much understanding.", zh: "然而，一长组几乎相同的题目可能只会增加疲劳，却不会带来多少理解。" },
          { en: "Useful homework usually has a clear purpose that students can recognize.", zh: "有效的作业通常有一个学生能够理解的明确目的。" },
          { en: "It might ask them to retrieve an idea from memory, apply it in a new situation, or notice what they still find confusing.", zh: "它可以要求学生从记忆中提取知识、把知识用于新情境，或发现自己仍然困惑的地方。" },
          { en: "Choice can also improve the experience without removing challenge.", zh: "适当的选择也能改善学习体验，同时不会降低挑战。" },
          { en: "For example, students could explain the same scientific concept through a diagram, a short paragraph, or a recorded message.", zh: "例如，学生可以用示意图、短文或录音来解释同一个科学概念。" },
          { en: "Each option requires accurate thinking, but allows different strengths to appear.", zh: "每一种方式都要求准确思考，同时也让不同的优势得以展现。" },
          { en: "Feedback is another essential part of the design.", zh: "反馈是作业设计中另一个不可缺少的部分。" },
          { en: "If completed work is never discussed, students may repeat the same mistakes and stop seeing the task as meaningful.", zh: "如果完成的作业从不被讨论，学生可能会重复同样的错误，也会逐渐觉得任务没有意义。" },
          { en: "Teachers do not need to mark every line, but they can highlight common problems and offer time for revision.", zh: "教师不必批改每一行，却可以指出共性问题，并留出修改时间。" },
          { en: "Well-designed homework respects students' time while asking them to think with care.", zh: "设计良好的作业既尊重学生的时间，也要求他们认真思考。" },
          { en: "The goal is not to make learning effortless, but to ensure that effort is directed toward something worth learning.", zh: "目标并不是让学习毫不费力，而是确保付出的努力真正指向值得学习的内容。" },
        ],
      },
      {
        id: "senior-advanced-forest-listening",
        level: "高考提高 · B1+–B2",
        cefr: "B1+–B2",
        estimatedWords: 228,
        title: "Listening to the Forest at Night",
        titleZh: "聆听夜晚的森林",
        genre: "科普阅读",
        topic: "人与自然",
        summary: "研究人员利用自动录音设备监测森林声音，从声景变化中了解生态健康。",
        sentences: [
          { en: "A forest at night may look still, yet its darkness is filled with information.", zh: "夜晚的森林看似静止，黑暗中却充满了信息。" },
          { en: "Frogs call after rain, insects produce steady rhythms, and birds sometimes sing before sunrise.", zh: "雨后青蛙鸣叫，昆虫发出稳定的节奏，有些鸟还会在日出前歌唱。" },
          { en: "Scientists are now using these sounds to study ecosystems without disturbing the animals that live there.", zh: "如今，科学家正利用这些声音研究生态系统，同时避免打扰生活在其中的动物。" },
          { en: "They place small weatherproof recorders on trees and program them to collect short samples throughout the day.", zh: "他们把小型防水录音设备固定在树上，并设置为全天定时采集短音频。" },
          { en: "One device can remain in the forest for weeks, gathering far more observations than a person could make alone.", zh: "一台设备可以在森林中连续工作数周，收集的观察资料远超一个人独自完成的数量。" },
          { en: "Back in the laboratory, computer programs turn the recordings into visual patterns called spectrograms.", zh: "回到实验室后，计算机程序会把录音转换成一种叫作声谱图的视觉图案。" },
          { en: "Researchers can search those patterns for particular calls or compare the overall sound of different places.", zh: "研究人员可以在图案中寻找特定叫声，也可以比较不同地点的整体声音。" },
          { en: "A rich mixture of sounds may suggest that many species are active in an area.", zh: "丰富多样的声音可能说明某一区域有许多物种正在活动。" },
          { en: "A sudden silence, by contrast, can warn scientists that something has changed.", zh: "相反，突然出现的寂静可能提醒科学家，环境发生了变化。" },
          { en: "However, sound alone cannot explain every change.", zh: "不过，声音本身并不能解释所有变化。" },
          { en: "Wind, traffic, and seasonal weather can affect a recording, while two species may produce surprisingly similar calls.", zh: "风声、交通和季节性天气都可能影响录音，而且两个物种的叫声有时会惊人地相似。" },
          { en: "For this reason, acoustic data works best when combined with field visits, photographs, and other evidence.", zh: "因此，声学数据与实地考察、照片和其他证据结合使用时效果最好。" },
          { en: "Even with these limits, forest listening offers an efficient way to notice changes across large areas and long periods.", zh: "即使存在这些限制，森林声音监测仍是一种高效方法，能够发现大范围、长时间内的变化。" },
          { en: "It also preserves a record that future scientists can examine with better tools.", zh: "它还保存了一份声音记录，未来的科学家可以利用更先进的工具重新研究。" },
          { en: "By paying attention to what we cannot easily see, researchers gain a fuller picture of life in the forest.", zh: "通过关注那些不容易看见的事物，研究人员能更完整地了解森林中的生命。" },
        ],
      },
    ],
  },
];

window.GRADED_ARTICLE_LIBRARIES = gradedArticleLibraries;
window.ALL_GRADED_ARTICLES = gradedArticleLibraries.flatMap((library) => library.items);
